using UnityEngine;
using UnityEngine.UI;
using System.Collections.Generic;

/// <summary>
/// AI-Guided Dissection — Provides a step-by-step medical walkthrough 
/// generated by AI for the selected organ.
/// </summary>
public class AIDissectionGuide : MonoBehaviour
{
    public Text guideTitleText;
    public Text guideBodyText;
    
    private string currentOrgan = "";
    private List<string> steps = new List<string>();
    private int currentStepIndex = 0;

    public void StartDissection(string organName)
    {
        currentOrgan = organName;
        currentStepIndex = 0;
        steps.Clear();

        if (guideTitleText != null) guideTitleText.text = "🔪 Dissecting: " + organName;
        if (guideBodyText != null) guideBodyText.text = "🔄 AI is preparing the dissection plan...";

        string prompt = "You are a surgical instructor. Provide a 5-6 step medical dissection guide for the " + organName + ". " +
                        "Format: Each step on a new line starting with 'STEP X:'. " +
                        "Be clinical and precise. No markdown.";

        GeminiService.Instance.SendPrompt(prompt, (response) => {
            ParseSteps(response);
            ShowStep(0);
        });
    }

    void ParseSteps(string raw)
    {
        string[] lines = raw.Split('\n');
        foreach (string line in lines)
        {
            if (line.Trim().StartsWith("STEP"))
                steps.Add(line.Trim());
        }
        
        if (steps.Count == 0 && !string.IsNullOrEmpty(raw))
            steps.Add(raw); // Fallback
    }

    public void NextStep()
    {
        if (steps.Count == 0) return;
        currentStepIndex = (currentStepIndex + 1) % steps.Count;
        ShowStep(currentStepIndex);
    }

    public void PreviousStep()
    {
        if (steps.Count == 0) return;
        currentStepIndex--;
        if (currentStepIndex < 0) currentStepIndex = steps.Count - 1;
        ShowStep(currentStepIndex);
    }

    void ShowStep(int index)
    {
        if (index >= 0 && index < steps.Count)
        {
            if (guideBodyText != null)
                guideBodyText.text = "<b>Step " + (index + 1) + " of " + steps.Count + "</b>\n\n" + steps[index];
        }
    }

    public void StopDissection()
    {
        steps.Clear();
        if (guideBodyText != null) guideBodyText.text = "Dissection complete. Select an organ to begin a new guide.";
    }
}
